// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgmiidfoahdxlurwjwqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnbWlpZGZvYWhkeGx1cndqd3FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzU3NDQsImV4cCI6MjA3MTY1MTc0NH0.DcgNUHXagr7aiNBGW--vHDJ2B9y7O4o5-P-orL-tL7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});